all: false
dir: '{{.InterfaceDir}}'
filename: mocks_test.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/enesanbar/url-shortener/internal/usecase/mapping/create:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks.go"
      pkgname: "test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      Repository: