---
debug: false
server:
  port: 9090
  context-path: /url-shortener
  healthcheck-path: /_hc

default-redirect: https://www.google.com

cache:
  inmemory:
    default-expiration: 1
    cleanup-interval: 30

usecases:
  redirect:
    retrier:
      wait-interval: 1000
      retry-count: 2

datasources:
  mongo:
    default:
      host: localhost:27017
      auth_db: admin
      username: root
      password: password
      name: url-shortener
      timeout: 5
      min-pool-size: 10
      max-pool-size: 10
      max-conn-idle-time: 10

  rabbitmq:
    connections:
      default:
        # host: localhost
        # port: "5672"
        username: guest
        password: guest
    
    channels:
      default:
        connection: default
        mandatory: false
        immediate: false

    # automatically create the exchange and queue of the same name (info.ServiceName)
    exchanges:
      url-shortener:
        channel: default
        exclusive: false
        type: direct
        durable: true
        auto-delete: false
        internal: false
        no-wait: false

    # TODO: configure prefetch count on the queue
    queues:
      default:
        channel: default
        durable: true
        auto-delete: false
        exclusive: false
        no-wait: false

    # ideally, this would be a separate service listening to the queue
    # but for simplicity, we are publishing and consuming on the same service
    bindings:
      - exchange: url-shortener
        queue: default
        no-wait: false
        routing-keys:
          - mappingCreated
          - mappingDeleted
          - mappingUpdated
          - mappingExpired
