// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/enesanbar/url-shortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *Repository) FindByCode(ctx context.Context, code string) (*domain.Mapping, error) {
	ret := _m.Called(ctx, code)

	var r0 *domain.Mapping
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Mapping); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Mapping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, mapping
func (_m *Repository) Store(ctx context.Context, mapping *domain.Mapping) (*domain.Mapping, error) {
	ret := _m.Called(ctx, mapping)

	var r0 *domain.Mapping
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Mapping) *domain.Mapping); ok {
		r0 = rf(ctx, mapping)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Mapping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Mapping) error); ok {
		r1 = rf(ctx, mapping)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
