// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/enesanbar/url-shortener/internal/domain"
	create "github.com/enesanbar/url-shortener/internal/usecase/mapping/create"

	mock "github.com/stretchr/testify/mock"
)

// CreateMappingUseCase is an autogenerated mock type for the CreateMappingUseCase type
type CreateMappingUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *CreateMappingUseCase) Execute(_a0 context.Context, _a1 *create.Request) (*domain.Mapping, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *domain.Mapping
	if rf, ok := ret.Get(0).(func(context.Context, *create.Request) *domain.Mapping); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Mapping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *create.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
