// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	getall "github.com/enesanbar/url-shortener/internal/usecase/mapping/getall"

	mock "github.com/stretchr/testify/mock"

	router "github.com/enesanbar/go-service/router"
)

// GetMappingsUsecase is an autogenerated mock type for the GetMappingsUsecase type
type GetMappingsUsecase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, request
func (_m *GetMappingsUsecase) Execute(ctx context.Context, request *getall.Request) (*router.PagedResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *router.PagedResponse
	if rf, ok := ret.Get(0).(func(context.Context, *getall.Request) *router.PagedResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*router.PagedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *getall.Request) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
