// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/enesanbar/url-shortener/internal/domain"
	get "github.com/enesanbar/url-shortener/internal/usecase/mapping/get"

	mock "github.com/stretchr/testify/mock"
)

// GetMappingUsecase is an autogenerated mock type for the GetMappingUsecase type
type GetMappingUsecase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, request
func (_m *GetMappingUsecase) Execute(ctx context.Context, request get.Request) (*domain.Mapping, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.Mapping
	if rf, ok := ret.Get(0).(func(context.Context, get.Request) *domain.Mapping); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Mapping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, get.Request) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
