name: Test & Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test -v -coverprofile=coverage/coverage.out ./...
          go tool cover -func=coverage/coverage.out > coverage/coverage.txt
          go tool cover -html=coverage/coverage.out -o coverage/coverage.html

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Display coverage in summary
        run: |
          echo '### Coverage Report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage/coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
